### ISSUE TITLE
email_get_template fails with an XML parsing error

### ISSUE THREAD

**Issue by ethankaminski** [nateleavitt/infusionsoft#54] opened 2016-11-14 04:10 UTC
On my current project (using Ruby 2.3.x, and version 1.1.9 of this gem), I receive the following error when trying to pull down an email template with `Infusionsoft.get_email_template(id)`:

```
REXML::UndefinedNamespaceException: Undefined prefix ex found
```

By dumping the raw HTML response, it appears that Infusionsoft is inserting the tag `<ex:nil/>` in its email template responses, which REXML dislikes.

If I patch XMLRPC::Client#call2 to strip that substring, then I can successfully fetch email templates. But, patching a core class strikes me as a hacky solution.

Are there any other ways to work around this issue? I'll attach a stack trace in a comment.

**Comment by ethankaminski** [comment] 2016-11-14 04:13
Here's the XMLRPC/Infusionsoft portion of the stack trace, on my dev instance:

```
/usr/lib/ruby/2.3.0/rexml/parsers/baseparser.rb:414:in `block in pull_event'
/usr/lib/ruby/2.3.0/set.rb:306:in `each_key'
/usr/lib/ruby/2.3.0/set.rb:306:in `each'
/usr/lib/ruby/2.3.0/rexml/parsers/baseparser.rb:412:in `pull_event'
/usr/lib/ruby/2.3.0/rexml/parsers/baseparser.rb:185:in `pull'
/usr/lib/ruby/2.3.0/rexml/parsers/streamparser.rb:19:in `parse'
/usr/lib/ruby/2.3.0/rexml/document.rb:242:in `parse_stream'
/usr/lib/ruby/2.3.0/xmlrpc/parser.rb:743:in `parse'
/usr/lib/ruby/2.3.0/xmlrpc/parser.rb:487:in `parseMethodResponse'
/usr/lib/ruby/2.3.0/xmlrpc/client.rb:288:in `call2'
/usr/lib/ruby/2.3.0/xmlrpc/client.rb:268:in `call'
/var/lib/gems/2.3.0/gems/infusionsoft-1.1.9/lib/infusionsoft/connection.rb:18:in `connection'
/var/lib/gems/2.3.0/gems/infusionsoft-1.1.9/lib/infusionsoft/request.rb:30:in `request'
/var/lib/gems/2.3.0/gems/infusionsoft-1.1.9/lib/infusionsoft/request.rb:6:in `get'
/var/lib/gems/2.3.0/gems/infusionsoft-1.1.9/lib/infusionsoft/client/email.rb:66:in `email_get_template'
/var/lib/gems/2.3.0/gems/infusionsoft-1.1.9/lib/infusionsoft.rb:19:in `method_missing'
```

And, for completeness, the rest of the stack trace:

```
(pry):3:in `__pry__'
/var/lib/gems/2.3.0/gems/pry-0.10.4/lib/pry/pry_instance.rb:355:in `eval'
/var/lib/gems/2.3.0/gems/pry-0.10.4/lib/pry/pry_instance.rb:355:in `evaluate_ruby'
/var/lib/gems/2.3.0/gems/pry-0.10.4/lib/pry/pry_instance.rb:323:in `handle_line'
/var/lib/gems/2.3.0/gems/pry-0.10.4/lib/pry/pry_instance.rb:243:in `block (2 levels) in eval'
/var/lib/gems/2.3.0/gems/pry-0.10.4/lib/pry/pry_instance.rb:242:in `catch'
/var/lib/gems/2.3.0/gems/pry-0.10.4/lib/pry/pry_instance.rb:242:in `block in eval'
/var/lib/gems/2.3.0/gems/pry-0.10.4/lib/pry/pry_instance.rb:241:in `catch'
/var/lib/gems/2.3.0/gems/pry-0.10.4/lib/pry/pry_instance.rb:241:in `eval'
/var/lib/gems/2.3.0/gems/pry-0.10.4/lib/pry/repl.rb:77:in `block in repl'
/var/lib/gems/2.3.0/gems/pry-0.10.4/lib/pry/repl.rb:67:in `loop'
/var/lib/gems/2.3.0/gems/pry-0.10.4/lib/pry/repl.rb:67:in `repl'
/var/lib/gems/2.3.0/gems/pry-0.10.4/lib/pry/repl.rb:38:in `block in start'
/var/lib/gems/2.3.0/gems/pry-0.10.4/lib/pry/input_lock.rb:61:in `__with_ownership'
/var/lib/gems/2.3.0/gems/pry-0.10.4/lib/pry/input_lock.rb:79:in `with_ownership'
/var/lib/gems/2.3.0/gems/pry-0.10.4/lib/pry/repl.rb:38:in `start'
/var/lib/gems/2.3.0/gems/pry-0.10.4/lib/pry/repl.rb:15:in `start'
/var/lib/gems/2.3.0/gems/pry-0.10.4/lib/pry/pry_class.rb:169:in `start'
/var/lib/gems/2.3.0/gems/pry-0.10.4/lib/pry/cli.rb:219:in `block in <top (required)>'
/var/lib/gems/2.3.0/gems/pry-0.10.4/lib/pry/cli.rb:83:in `block in parse_options'
/var/lib/gems/2.3.0/gems/pry-0.10.4/lib/pry/cli.rb:83:in `each'
/var/lib/gems/2.3.0/gems/pry-0.10.4/lib/pry/cli.rb:83:in `parse_options'
/var/lib/gems/2.3.0/gems/pry-0.10.4/bin/pry:16:in `<top (required)>'
/usr/local/bin/pry:23:in `load'
/usr/local/bin/pry:23:in `<main>'
```

**Comment by nateleavitt** [comment] 2017-02-07 04:12
@ethankaminski Sorry for the late follow up. Did you ever figure out a way to solve this?

**Comment by ethankaminski** [comment] 2017-02-07 06:10
Not really, no - I've got something for me specifically, but nothing that I'd be comfortable submitting as a pull request. The best I came up with is a monkeypatch to `XMLRPC::Client`. That works for my application (because I know there won't be any unintended side-effects), but seems like an iffy solution for a gem.

On the other hand, the entirety of the relevant code seems to be buried pretty deep in XMLRPC.

Here's the hack I've used, if anyone else wants it (please excuse the annoyed comment about the API):

    # monkeypatch *the entire XMLRPC class* because of
    # one little spurious unhandled tag in Infusionsoft's API
    module HackXMLRPC
    	def do_rpc(arg_1, arg_2)
    		data = super(arg_1, arg_2)
    		data.gsub('<ex:nil/>', '')
    	end
    end
    module XMLRPC
    	class Client
    		prepend HackXMLRPC
    	end
    end

**Comment by jaredjackson** [comment] 2017-04-28 22:38
I tested a fresh app with Rails 4.2.8, Ruby 2.3.x and 1.1.9 of this gem and cannot reproduce. Also tested with a Rails 5.0.x production app, Ruby 2.3.x and 1.1.9 if this gem and cannot reproduce.

**Comment by nateleavitt** [comment] 2017-06-20 18:54
I also cannot reproduce. @ethankaminski are you still having this issue?

**Comment by nateleavitt** [comment] 2018-07-24 05:41
Closing because of non-response. Reopen if still an issue.

**Closed by nateleavitt** 2018-07-24 05:41 UTC

**Comment by jaredjackson** [comment] 2019-06-08 17:07
For anyone else that sees this. I ran into this problem again recently and addressed it with the monkey patch from @ethankaminski ... placed it in an initializer -> hack_xmlrpc.rb
