### ISSUE TITLE
Rare but showstopper OpenSSL errors with xmlrpc 

### ISSUE THREAD

**Issue by sneakernets** [nateleavitt/infusionsoft#70] opened 2018-02-20 20:25 UTC
I'm getting some interesting errors occasionally when sending simple commands, like removing contacts from a group:

```
OpenSSL::SSL::SSLError: SSL_connect SYSCALL returned=5 errno=0 state=unknown state
/home/testbed/.rvm/gems/ruby-2.4.1@global/gems/xmlrpc-0.2.1/lib/xmlrpc/client.rb:495:in `do_rpc'
/home/testbed/.rvm/gems/ruby-2.4.1@global/gems/xmlrpc-0.2.1/lib/xmlrpc/client.rb:287:in `call2'
/home/testbed/.rvm/gems/ruby-2.4.1@global/gems/xmlrpc-0.2.1/lib/xmlrpc/client.rb:268:in `call'
/home/testbed/.rvm/gems/ruby-2.4.1/gems/infusionsoft-1.2.0/lib/infusionsoft/connection.rb:18:in `connection'
/home/testbed/.rvm/gems/ruby-2.4.1/gems/infusionsoft-1.2.0/lib/infusionsoft/request.rb:30:in `request'
/home/testbed/.rvm/gems/ruby-2.4.1/gems/infusionsoft-1.2.0/lib/infusionsoft/request.rb:6:in `get'
/home/testbed/.rvm/gems/ruby-2.4.1/gems/infusionsoft-1.2.0/lib/infusionsoft/client/contact.rb:134:in `contact_remove_from_group'
/home/testbed/.rvm/gems/ruby-2.4.1/gems/infusionsoft-1.2.0/lib/infusionsoft.rb:19:in `method_missing'
```

In the meantime I'm having to catch this error in a rescue block, to try again after a certain number of seconds. The gem seems unaware that this situation can happen.

**Comment by sneakernets** [comment] 2018-03-12 15:54
I'm still getting these sometimes, as recently as 7 AM (CDT) . Do I need to go to oauth now? Would that be more reliable? Having to rescue every possible API call is a pain.

**Comment by rafaldyrda** [comment] 2018-03-14 17:26
I too am having this issue now. Is there a recommended solution?

**Comment by sneakernets** [comment] 2018-03-26 14:32
The only thing I've found is to account for every single error I've seen so far, catch it, and try again. I know that's tedious, but it's the only way I've been able to keep my scripts running for more than an hour.

**Comment by nateleavitt** [comment] 2018-07-24 05:39
Hey guys.. sorry for the late response. Are you guys still seeing these errors?

**Comment by nateleavitt** [comment] 2018-07-24 06:05
Also adding here. Try this: https://github.com/nateleavitt/infusionsoft/issues/71#issuecomment-407291406

**Comment by nateleavitt** [comment] 2018-08-09 19:58
Closing and marking this as a duplicate of https://github.com/nateleavitt/infusionsoft/issues/71#issuecomment-407291406

**Closed by nateleavitt** 2018-08-09 19:58 UTC
